---
collections:
    change_requests:
        xml_name: 'change-requests'
        media_type: 'application/vnd.net.juniper.space.configuration-management.change-requests+xml;version=1'
        url: '/api/space/configuration-management/change-requests'
        resource_type: 'configuration_management.change_request'
        methods:
            v2_single:
                name: '-' # Use parent's URL
                request_type: 'application/vnd.net.juniper.space.configuration-management.change-request+xml;version=2;charset=UTF-8'
                request_template: 'change_request_v2_single.tpl'
            v2_multiple:
                name: '-' # Use parent's URL
                request_type: 'application/vnd.net.juniper.space.configuration-management.change-requests+xml;version=2;charset=UTF-8'
                request_template: 'change_request_v2_multiple.tpl'
            v2_multiple_async:
                name: '-' # Use parent's URL
                request_type: 'application/vnd.net.juniper.space.configuration-management.change-requests+xml;version=2;charset=UTF-8'
                request_template: 'change_request_v2_multiple.tpl'
                response_type: 'application/vnd.net.juniper.space.job-management.task+xml;version=1'
    cli_configlets:
        xml_name: 'cli-configlets'
        media_type: 'application/vnd.net.juniper.space.configuration-management.cli-configlets+xml;version=2;charset=UTF-8'
        retain_charset_in_accept: True
        url: '/api/space/configuration-management/cli-configlets'
        resource_type: 'configuration_management.cli_configlet'
        methods:
            cli_configlets_by_context:
                name: 'cli-configlets-by-context'
                request_type: 'application/vnd.net.juniper.space.configuration-management.cli-configlet-by-context+xml;version=2;charset=UTF-8'
                request_template: 'cli_configlets_by_context.tpl'
                response_type: 'application/vnd.net.juniper.space.configuration-management.cli-configlets+xml;version=2;charset=UTF-8'
                retain_charset_in_accept: True

resources:
    change_request:
        xml_name: 'change-request'
        media_type: 'application/vnd.net.juniper.space.configuration-management.change-request+xml;version=1'
        collection_name: 'change_requests'
        service_url: '/api/space/configuration-management'

    cli_configlet:
        xml_name: 'cli-configlet'
        media_type: 'application/vnd.net.juniper.space.configuration-management.view-cli-configlet+xml;version=1;charset=UTF-8'
        retain_charset_in_accept: True
        collection_name: 'cli_configlets'
        service_url: '/api/space/configuration-management'
        collections:
            cli_configlet_params:
                name: 'cli-configlet-params'
                xml_name: 'cli-configlet-params'
                media_type: 'application/vnd.net.juniper.space.configuration-management.cli-configlet-params+xml;version=2;charset=UTF-8'
                retain_charset_in_accept: True
                resource_type: 'configuration_management.cli_configlet_param'
            cli_configlet_pages:
                name: 'cli-configlet-pages'
                xml_name: 'cli-configlet-pages'
                media_type: 'application/vnd.net.juniper.space.configuration-management.cli-configlet-pages+xml;version=2;charset=UTF-8'
                retain_charset_in_accept: True
                resource_type: 'configuration_management.cli_configlet_page'
        methods:
            apply_configlet:
                name: 'apply-configlet'
                request_type: 'application/vnd.net.juniper.space.configuration-management.apply-configlet+xml;version=2;charset=UTF-8'
                request_template: 'apply_configlet.tpl'
                response_type: 'application/vnd.net.juniper.space.job-management.task+xml;version=1'

    cli_configlet_param:
        xml_name: 'cli-configlet-param'
        media_type: 'application/vnd.net.juniper.space.configuration-management.cli-configlet-param+xml;version=2;charset=UTF-8'
        retain_charset_in_accept: True
        collection_name: 'cli_configlet_params'
        service_url: '/api/space/configuration-management'
    cli_configlet_page:
        xml_name: 'cli-configlet-page'
        media_type: 'application/vnd.net.juniper.space.configuration-management.cli-configlet-page+xml;version=2;charset=UTF-8'
        retain_charset_in_accept: True
        collection_name: 'cli_configlet_pages'
        service_url: '/api/space/configuration-management'

methods:
...